insert into Statut(id_statut, libelle, dtype) values(1, 'Nouveau', 'etab');
insert into Statut(id_statut, libelle, dtype) values(2, 'Aucune IP', 'etab');
insert into Statut(id_statut, libelle, dtype) values(3, 'En valication', 'etab');
insert into Statut(id_statut, libelle, dtype) values(4, 'Validé', 'etab');
insert into Statut(id_statut, libelle, dtype) values(5, 'Attestation demandée', 'etab');
insert into Statut(id_statut, libelle, dtype) values(6, 'Nouvelle IP', 'ip');
insert into Statut(id_statut, libelle, dtype) values(7, 'Attestation demandée', 'ip');
insert into Statut(id_statut, libelle, dtype) values(8, 'IP Validée', 'ip');
insert into Statut(id_statut, libelle, dtype) values(9, 'Aucune IP', 'ip');

insert into type_etablissement(id, libelle) values(1, 'Universités, grandes écoles, écoles de formation spécialisées');
insert into type_etablissement(id, libelle) values(2, 'CHR-CHU');
insert into type_etablissement(id, libelle) values(3, 'Etablissements de santé (autres que CHR-CHU)');
insert into type_etablissement(id, libelle) values(4, 'Ecoles françaises à l étranger');
insert into type_etablissement(id, libelle) values(5, 'Etablissements publics administratifs');
insert into type_etablissement(id, libelle) values(6, 'Organismes de recherche');
insert into type_etablissement(id, libelle) values(7, 'Etablissements publics de coopération scientifique');
insert into type_etablissement(id, libelle) values(8, 'Etablissements publics de coopération culturelle');
insert into type_etablissement(id, libelle) values(9, 'Etablissements publics à caractère industriel et commercial');
insert into type_etablissement(id, libelle) values(10, 'Fondation reconnues d utilité publique');
insert into type_etablissement(id, libelle) values(11, 'GIP');
insert into type_etablissement(id, libelle) values(12, 'Réseau Latitude France');
insert into type_etablissement(id, libelle) values(13, 'Bibliothèques de lecture publique.');
